apiVersion: batch/v1
kind: Job
metadata:
  name: postman-api-tests
spec:
  template:
    spec:
      containers:
      - name: postman-runner
        image: postman-tests:latest
        imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
          - |
            newman run collections/ultimate_api.postman_collection.json \
            -e environments/qa_postman_environment.json \
            --suppress-exit-code \
            -r cli,htmlextra,allure,elasticsearch \
            --reporter-elasticsearch-url http://elasticsearch-service:9200 \
            --reporter-elasticsearch-index postman-logs \
            --reporter-allure-export allure-results
      restartPolicy: Never
  backoffLimit: 1

