name: Automated Postman Tests

on:
  workflow_dispatch: # Только ручной запуск по кнопке на сайте

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Newman and Reporters
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
        npm install -g newman-reporter-allure

    - name: Run Postman Tests
      run: |
        newman run collections/ultimate_api.postman_collection.json -e environments/qa_postman_environment.json -r cli,htmlextra,allure --reporter-allure-export allure-results
      continue-on-error: true

    - name: Upload htmlextra Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: postman-html-report
        path: newman/
        retention-days: 5

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

        - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: allure-history


